apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.fullname" . }}-config
  labels:
    {{- include "db.labels" . | nindent 4 }}
data:
  # PostgreSQL 초기화 스크립트
  init.sql: |
{{- with .Values.postgresql.initdbScripts }}
{{ index . "init.sql" | indent 4 }}
{{- end }}
  
  # PostgreSQL 설정
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 512MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 4GB
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.UTF-8'
    lc_monetary = 'en_US.UTF-8'
    lc_numeric = 'en_US.UTF-8'
    lc_time = 'en_US.UTF-8'
    default_text_search_config = 'pg_catalog.english' 
