apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}-secrets
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Configuration
  DB_HOST: {{ .Values.secrets.DB_HOST | quote }}
  DB_PORT: {{ .Values.secrets.DB_PORT | quote }}
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  DB_DATABASE: {{ .Values.secrets.DB_DATABASE | quote }}

  # SMTP Configuration
  SMTP_HOST: {{ .Values.secrets.SMTP_HOST | default "" | quote }}
  SMTP_PORT: {{ .Values.secrets.SMTP_PORT | default "" | quote }}
  SMTP_USER: {{ .Values.secrets.SMTP_USER | default "" | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.SMTP_PASSWORD | default "" | quote }}
  SMTP_ENCRYPTION: {{ .Values.secrets.SMTP_ENCRYPTION | default "" | quote }}
  SMTP_AUTH_MODE: {{ .Values.secrets.SMTP_AUTH_MODE | default "" | quote }}