replicaCount: 1

image:
  repository: mautic/mautic
  pullPolicy: IfNotPresent
  tag: "5-apache"

imagePullSecrets: [ ]
nameOverride: "mautic"
fullnameOverride: "mautic"

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: mautic.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mautic-tls
      hosts:
        - mautic.example.com

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: MAUTIC_DB_HOST
    value: "${MYSQL_HOST}"
  - name: MAUTIC_DB_PORT
    value: "${MYSQL_PORT}"
  - name: MAUTIC_DB_DATABASE
    value: "${MYSQL_DATABASE}"
  - name: MAUTIC_DB_USER
    value: "${MYSQL_USER}"
  - name: MAUTIC_DB_PASSWORD
    value: "${MYSQL_PASSWORD}"
  - name: MAUTIC_URL
    value: "https://mautic.cd80.run"
  - name: PHP_MEMORY_LIMIT
    value: "1G"
  - name: PHP_MAX_EXECUTION_TIME
    value: "300"
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: "100M"
  - name: PHP_POST_MAX_SIZE
    value: "100M"
  - name: MAUTIC_TRUSTED_PROXIES
    value: "0.0.0.0/0"
  - name: MAUTIC_RUN_CRON_JOBS
    value: "true"
  - name: MAUTIC_CRON_HUBSPOT
    value: "false"
  - name: MAUTIC_CRON_SALESFORCE
    value: "false"
  - name: MAUTIC_CRON_PIPEDRIVE
    value: "false"
  - name: MAUTIC_CRON_ZOHO
    value: "false"
  - name: MAUTIC_CRON_SUGARCRM
    value: "false"
  - name: MAUTIC_CRON_DYNAMICS
    value: "false"
  - name: MAUTIC_MESSENGER_DSN_EMAIL
    value: "doctrine://default"
  - name: MAUTIC_MESSENGER_DSN_HIT
    value: "doctrine://default"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: { }

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }

secrets:
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USER: "mautic"
  DB_PASSWD: "mautic"
  DB_NAME: "mautic"

  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_ENCRYPTION: ""
  SMTP_AUTH_MODE: ""

mariadb:
  enabled: true
  auth:
    database: mautic
    username: mautic
    password: mautic
    rootPassword: mautic
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  architecture: standalone
  image:
    tag: "10.11.4-debian-11-r0"
  volumePermissions:
    enabled: true
  metrics:
    enabled: false
